### ISSUE TITLE
'Failed to lookup fuelbed information'

### ISSUE THREAD

**Issue by smitimittal** [pnwairfire/bluesky#238]
I am trying to run fuelbeds on a json file containing perimeter coordinates for the Nelson fire. Even though it is formatted exactly as test examples provided, I am encountering the error message: "Failed to lookup fuelbed information". What are some potential reasons this could be happening? I am able to run test cases successfully, so there doesn't seem to be an issue with my environment setup. I'm attaching the txt version of the json file used and the --log-level DEBUG output.
[debug_nelson_perimeter.txt](https://github.com/pnwairfire/bluesky/files/7709871/debug_nelson_perimeter.txt)
[nelson_perimeter.txt](https://github.com/pnwairfire/bluesky/files/7709872/nelson_perimeter.txt)

**Comment by smitimittal** [comment]
Update: I also tried using lesser points along the perimeter and rounding off the lat/long values to 5 decimal places to reduce the precision required. I tried another fire too. None of these modified versions worked.

**Comment by jdubowy** [comment]
The call to `zonal_stats` in lookup.py is returning `None` values for that perimeter when using v2 FCCS data (which is the default).  I tried v1 of the FCCS data, and it returned FCCS #0, bare ground (100%).  So, there seems to be a gap specifically in the v2 data.  It would be helpful to visualize the data in  the .nc file, but I've run into some problems installing and running various NetCDF tools.  I'll look into this soon, and I'll post an update once I have insight into the underlying data.

If you'd like to look at the underlying, grided FCCS data, you can download the NetCDF file [here](https://github.com/pnwairfire/fccsmap/raw/master/fccsmap/data/fccs2_fuelload.nc).

**Comment by jdubowy** [comment]
I've written a script to visualize the FCCS data in the neighborhood of the Nelson perimeter. This is using FCCS v1:

![image](https://user-images.githubusercontent.com/171183/146276974-ebb2f2fd-e018-4530-98c6-e968fa182f4d.png)

And this is using FCCS v2:

![image](https://user-images.githubusercontent.com/171183/146277077-a6b57e50-441e-4e29-9f17-c57b0bf68476.png)

I'm not sure why v1 is returning nothing rather than #0 and #41. The logic that seems to be missing the 0's is in  `rasterstats.zonal_stats`.  It doesn't do this for other locations.  We'll have to look into this more.

**Comment by smitimittal** [comment]
Thank you for the update and for diving into this issue! Appreciate you looking into it.

**Comment by Porkking** [comment]
Are there any updates in the new version so far? I have the same issue.I am running multiple fires in Florida. I tried to separate 640 fires into 32 input files. About 10 files are crushed due to the same error. It is hard to run a case with huge amount of fires due to this issue now.

**Comment by jdubowy** [comment]
I unfortunately haven't had time to work on this.  If you'd like to help investigate, you might want to look at `rasterstats.zonal_stats`, since that seemed to be failing to return FCCS Ids that appear to be in the netcdf file.

**Comment by Porkking** [comment]
Hi Joel, I look at the FccsLookUp object. I guess my issue is the fccs_id is 0 at the latitude and longitude I provided. The code enlarges the search region:
```
            if self._has_high_percent_of_ignored(stats):
                logging.debug("Resampling 3 * grid resoluation")
                new_geo_data = self._transform_points(geo_data,
                    3*self.grid_resolution)
                stats = self._look_up(new_geo_data)
```
But it still does not find any valid fccs_id. I try to increase the parameter (eg: 3->9) and it works. I am not sure why 3 is selected. What is your suggestion to treat the location where the fccs_id is invalid? Thanks.

**Comment by Porkking** [comment]
I also checked @smitimittal 's issue. One thing I do not understand is the counts function used in 
```
    def _look_up(self, geo_data):
        s = geometry.shape(geo_data)
        s = ops.transform(self.projector, s)

        def counts(x):
            counts = defaultdict(lambda: 0)
            for i in range(len(x.data)):
                for j in range(len(x.data[i])):
                    if not x.mask[i][j]:
                        # Note: if x.data[i][j] < 0, it's up
                        # to calling code to deal with it
                        counts[x.data[i][j]] += 1
            return dict(counts)

        stats = zonal_stats(s, self.gridfile_specifier,
            add_stats={'counts':counts})
```
The reason why zonal_stats does not retrieve the stats is because of x data mask. The mask of x data is
```
[[ True  True]
 [ True  True]]
```
So, the counts matrix does not store the information (the if part is not executed). I simply remove the not before x.mask[i][j], it returns the result:
```
{'grid_cells': 4, 'fuelbeds': {'41': {'percent': 100.0, 'grid_cells': 1}}, 'area': 443544.6916476172, 'units': 'm^2'}
```

**Comment by jdubowy** [comment]
In response to your first comment, the default behavior when looking up FCCS Id(s) for a point is to use an area equal to 4 grid cells around the point.  As you saw, if no valid FCCS Ids are found, the dimensions of the look-up area are multiplied by , an area of 36 grid cells (`(2 grid cells * 3)^2)`) is used.  I unfortunately don't have an answer as to why a factor of `3` is used.  That was decided years ago with the consultation of people who are no longer colleagues.  There's actually an issue (https://github.com/pnwairfire/fccsmap/issues/13) to support setting the look-up area based on fire size.  That issue suggests having that as an option, but I think it should probably be the default behavior.

If you increase the area enough, you'll eventually get valid FCCS Ids, but using a factor of 9, as you did, will result in an area of `(9+9)^2 = 324` grid cells, which I imagine is way to large an area to be considering.

**Comment by jdubowy** [comment]
Thanks for looking into our use of zonal stats.   I need to take a look at the code before I respond.

**Comment by jdubowy** [comment]
I've update `fccsmap` (`v3.0.2`) so that it

**Comment by jdubowy** [comment]
I've updated fccsmap (`v3.0.2`) so that it considers grid cells that are partially within the look-up area if configured to do so (`use_all_grid_cells=true`) or if all cells are partial (as is the case for the Nelson fire with FCCS v2).  Upgrading fccsmap in bluesky has caused an npm installation error, which I'm working on now.

**Comment by Porkking** [comment]
One more question about the invalid fuel type and fccs map. The point I met this error message is a place in Florida agricultural land (near Okeechobee). I tried enlarge the number from 3 to 6 (you are correct, really large area if I change to 6) and it returns no valid fuel type except 0. FCCS does not include agricultural land right? Also, blueSKY website version calls 0 type fuel as Miscellaneous light fuel. It can return some emissions if I choose this type of fuel. Do you have any method to treat this invalid fuel type? Thanks.

**Comment by jdubowy** [comment]
I think that there is a fair amount of agricultural land classified as FCCS #0 in our FCCS data.  The default fuel loading values for #0 are all zeros.  So, you should get zero emissions unless you provide custom, non-zero fuel loadings, which is what we do on our website (and which is why it's re-labeled as 'Miscellaneous light fuel').
